### ISSUE TITLE
Meta-Issue: "Soft" ToDo's before Beta Release

### ISSUE THREAD

**Issue by alexmorley** [flatironinstitute/mountainlab-js#56]
### Docs
- [ ] Audit Docs, have naive user install/test/explain
- [ ] Resolve #37 (Install Instructions)

### Other
- [ ] Go through error messages and make sure at least most of them are helpful
- [ ] Add a CHANGELOG.md

### Community
- [ ] Add contributing.md
- [ ] Add Issue Template
- [ ] ?Add PR Template
